/**
 * Audit Log Constants
 * Centralized definitions for event types and entity types
 */

/**
 * All valid event types for audit logs
 */
export const AUDIT_EVENT_TYPES = {
  // Customer events
  CUSTOMER_CREATED: "CUSTOMER_CREATED",
  CUSTOMER_UPDATED: "CUSTOMER_UPDATED",
  CUSTOMER_DELETED: "CUSTOMER_DELETED",

  // Business events
  BUSINESS_STATUS_CHANGED: "BUSINESS_STATUS_CHANGED",

  // Inventory events
  INVENTORY_ADJUSTED: "INVENTORY_ADJUSTED",
  INVENTORY_TRANSFER: "INVENTORY_TRANSFER",

  // Invitation events
  INVITATION_CREATED: "INVITATION_CREATED",
  INVITATION_ACCEPTED: "INVITATION_ACCEPTED",
  INVITATION_REVOKED: "INVITATION_REVOKED",
  INVITATION_RESENT: "INVITATION_RESENT",

  // Outlet events
  OUTLET_CREATED: "OUTLET_CREATED",
  OUTLET_UPDATED: "OUTLET_UPDATED",
  OUTLET_DELETED: "OUTLET_DELETED",

  // Password events
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  PASSWORD_RESET: "PASSWORD_RESET",

  // Price tier events
  PRICE_TIER_CREATED: "PRICE_TIER_CREATED",
  PRICE_TIER_UPDATED: "PRICE_TIER_UPDATED",
  PRICE_TIER_DELETED: "PRICE_TIER_DELETED",

  // Product events
  PRODUCT_CREATED: "PRODUCT_CREATED",
  PRODUCT_UPDATED: "PRODUCT_UPDATED",
  PRODUCT_DELETED: "PRODUCT_DELETED",
  PRODUCT_REACTIVATED: "PRODUCT_REACTIVATED",
  PRODUCT_PRICE_SET: "PRODUCT_PRICE_SET",

  // Purchase order events
  PURCHASE_ORDER_CREATED: "PURCHASE_ORDER_CREATED",
  PURCHASE_ORDER_UPDATED: "PURCHASE_ORDER_UPDATED",
  PURCHASE_ORDER_RECEIVED: "PURCHASE_ORDER_RECEIVED",
  PURCHASE_ORDER_CANCELLED: "PURCHASE_ORDER_CANCELLED",

  // Sale events
  SALE_CREATED: "SALE_CREATED",
  SALE_COMPLETED: "SALE_COMPLETED",
  SALE_PAYMENT_ADDED: "SALE_PAYMENT_ADDED",
  SALE_REFUNDED: "SALE_REFUNDED",
  SALE_VOID: "SALE_VOID",
  SALE_CANCELLED: "SALE_CANCELLED",

  // Supplier events
  SUPPLIER_CREATED: "SUPPLIER_CREATED",
  SUPPLIER_UPDATED: "SUPPLIER_UPDATED",
  SUPPLIER_DELETED: "SUPPLIER_DELETED",

  // User events
  USER_LOGIN: "USER_LOGIN",
  USER_LOGGED_OUT: "USER_LOGGED_OUT",
  USER_SESSION_REVOKED: "USER_SESSION_REVOKED",
  USER_ALL_SESSIONS_REVOKED: "USER_ALL_SESSIONS_REVOKED",
  USER_IMPERSONATION_STARTED: "USER_IMPERSONATION_STARTED",
  USER_PASSWORD_FORCE_RESET: "USER_PASSWORD_FORCE_RESET",
  USER_ACTIVATED: "USER_ACTIVATED",
  USER_DEACTIVATED: "USER_DEACTIVATED",
  USER_CREATED: "USER_CREATED",
  USER_UPDATED: "USER_UPDATED",
  USER_DELETED: "USER_DELETED",
  USER_OUTLET_ASSIGNED: "USER_OUTLET_ASSIGNED",
  USER_OUTLET_REMOVED: "USER_OUTLET_REMOVED",

  // Warehouse events
  WAREHOUSE_CREATED: "WAREHOUSE_CREATED",
  WAREHOUSE_UPDATED: "WAREHOUSE_UPDATED",
  WAREHOUSE_DELETED: "WAREHOUSE_DELETED",
};

/**
 * All valid entity types for audit logs
 */
export const AUDIT_ENTITY_TYPES = {
  CUSTOMER: "Customer",
  BUSINESS: "Business",
  INVENTORY: "Inventory",
  INVITATION: "Invitation",
  OUTLET: "Outlet",
  OUTLET_USER: "OutletUser",
  POS_ORDER: "PosOrder",
  PRICE_TIER: "PriceTier",
  PRODUCT: "Product",
  PRODUCT_PRICE_TIER: "ProductPriceTier",
  PURCHASE_ORDER: "PurchaseOrder",
  SALE: "Sale",
  SUPPLIER: "Supplier",
  STOCK_MOVEMENT: "StockMovement",
  USER: "User",
  WAREHOUSE: "Warehouse",
};

/**
 * Get list of all event types (for API responses)
 */
export function getAllEventTypes() {
  return Object.values(AUDIT_EVENT_TYPES).sort();
}

/**
 * Get list of all entity types (for API responses)
 */
export function getAllEntityTypes() {
  return Object.values(AUDIT_ENTITY_TYPES).sort();
}
